### PR TITLE
Fix filter empty categories

### PR DESCRIPTION
**Pull request by thinkh**
closes https://github.com/datavisyn/lineup_app/issues/13

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 

### Summary

Filters the empty categories before creating actual categories.

### CODE REVIEW

**Comment by sgratzl** [comment]
according to the definition of `ICategoricalColumnDesc` categories cannot be null. Thus it is a configuration error and not a lineup error

**Comment by thinkh** [comment]
Ok, but if the dataset contains empty categories? Then the whole LineUp breaks and the user doesn't get any feedback (unless he opens the console...).

I suggest(ed) to ignore empty categories and treat them as missing values.

**Comment by sgratzl** [comment]
so you mean: 

https://github.com/datavisyn/lineupjs/blob/f7198ce9cf9e75f53f72f57dd4aae705fa6536e4/src/model/CategoricalColumn.ts#L44-L51

and 

https://github.com/datavisyn/lineupjs/blob/f7198ce9cf9e75f53f72f57dd4aae705fa6536e4/src/builder/column/CategoricalColumnBuilder.ts#L71-L78

**Comment by thinkh** [comment]
Good to know that LineUp treates missing values already.

The original error occurs when downloading and importing the same dataset again (see https://github.com/datavisyn/lineup_app/issues/13). It might be that either the export or import does not treat missing categories correctly.

Therefore you might be right, that the error handling/empty categories must be handled in the lineup_app code.

**Pull request closed without merging**
