### PR TITLE
Rename `Don't care` to `Implicit` in sort dialog

### PR DESCRIPTION
**Pull request by thinkh**
**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 

### Summary

See https://github.com/datavisyn/lineupjs/pull/26#issuecomment-397329151.

### CODE REVIEW

**Comment by mstreit** [comment]
How about calling it 'Unsorted' and providing it as third option?

**Comment by sgratzl** [comment]
there is now a conflict that needs to solved first

**Comment by thinkh** [comment]
I don't care.

**Comment by mstreit** [comment]
I care ;)

how about 'no sorting'?
the fact that it can still be somehow sorted if the dataset comes with a sorting is not really relevant to the user in this context.

...and the option should be the last one in the list.

**Pull request closed without merging**
